"""Allow duplicate video

Revision ID: 746de3231421
Revises: 3efb3d0930f0
Create Date: 2024-08-13 10:04:58.852352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '746de3231421'
down_revision: Union[str, None] = '3efb3d0930f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_external_video_id_key', 'video', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('video_external_video_id_key', 'video', ['external_video_id'])
    # ### end Alembic commands ###
