"""Allow cascading delete 3

Revision ID: 852120534c92
Revises: 8a9d6d5ffa97
Create Date: 2024-08-13 15:37:22.752775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '852120534c92'
down_revision: Union[str, None] = '8a9d6d5ffa97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('video_session_id_fkey', 'video', type_='foreignkey')
    op.create_foreign_key(None, 'video', 'session', ['session_id'], ['session_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video', type_='foreignkey')
    op.create_foreign_key('video_session_id_fkey', 'video', 'session', ['session_id'], ['session_id'])
    # ### end Alembic commands ###
