"""Allow cascading delete 2

Revision ID: 8a9d6d5ffa97
Revises: 279e3b9182ac
Create Date: 2024-08-13 15:31:32.898583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9d6d5ffa97'
down_revision: Union[str, None] = '279e3b9182ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
